name = "ci-runner-new-local"
executor = "local"
concurrent = 10
log_level = "debug"
listen_address = ":9252"
url = "xxx/fconfigci-new"
artifact_path = "fdevtest-generic-local/fdev-ci-artifacts-rel"
[minio]
plugins_bucket = "fdev-ci-plugins-rel"
