image: xxx/mbpe-public-docker-local/library/fdev-helper:latest

stages:
  - maven-build
  - deploy

variables:
  CI_REGISTRY: "xxx/mbpe-public-docker-local"
  CI_REGISTRY_IMAGE: "xxx/mbpe-public-docker-local/library/fdev-task"
  CI_REGISTRY_USER: "spdb-mbpe"
  CI_REGISTRY_PASSWORD: "xxx"


maven-build:
  image: xxx/mbpe-public-docker-local/library/maven:3-jdk-8
  stage: maven-build
#   variables:
#     CI_DEBUG_TRACE: "false"
  script:
    - mvn clean package -U -Dmaven.test.skip=true
    # - mvn sonar:sonar  -Dsonar.host.url=xxx -Dsonar.login=e6195643c4266cb57619e1cf4a62385ff61e49b9 -Dsonar.scm.provider=git
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 min
  only:
    - /^SIT.*$/
    - /^sit.*$/
    - schedules
    - /^PRO.*$/
    - /^pro.*$/


k8s-deploy:
  stage: deploy
  services:
    - xxx/mbpe-public-docker-local/library/docker:dind-spdb
  script:
    - build_fdev.py
    - deploy_fdev.py
  only:
    - /^SIT.*$/
    - /^sit.*$/
    - schedules
    - /^PRO.*$/
    - /^pro.*$/
